# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 130, 131, 51))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 190, 131, 51))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.shidu = QtWidgets.QLabel(self.centralwidget)
        self.shidu.setGeometry(QtCore.QRect(220, 190, 141, 51))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.shidu.setFont(font)
        self.shidu.setObjectName("shidu")
        self.wendu = QtWidgets.QLabel(self.centralwidget)
        self.wendu.setGeometry(QtCore.QRect(220, 130, 141, 51))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.wendu.setFont(font)
        self.wendu.setObjectName("wendu")
        self.caiji = QtWidgets.QPushButton(self.centralwidget)
        self.caiji.setGeometry(QtCore.QRect(90, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.caiji.setFont(font)
        self.caiji.setObjectName("caiji")
        self.kai = QtWidgets.QPushButton(self.centralwidget)
        self.kai.setGeometry(QtCore.QRect(280, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.kai.setFont(font)
        self.kai.setObjectName("kai")
        self.guan = QtWidgets.QPushButton(self.centralwidget)
        self.guan.setGeometry(QtCore.QRect(420, 290, 91, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.guan.setFont(font)
        self.guan.setObjectName("guan")
        self.on = QtWidgets.QLabel(self.centralwidget)
        self.on.setGeometry(QtCore.QRect(310, 110, 161, 151))
        self.on.setText("")
        self.on.setPixmap(QtGui.QPixmap(":/1/风扇/风扇/fan4.png"))
        self.on.setScaledContents(True)
        self.on.setObjectName("on")
        self.off = QtWidgets.QLabel(self.centralwidget)
        self.off.setGeometry(QtCore.QRect(310, 110, 161, 151))
        self.off.setText("")
        self.off.setPixmap(QtGui.QPixmap(":/1/风扇/风扇/fan3.png"))
        self.off.setScaledContents(True)
        self.off.setObjectName("off")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "温度值："))
        self.label_2.setText(_translate("MainWindow", "湿度值："))
        self.shidu.setText(_translate("MainWindow", "0"))
        self.wendu.setText(_translate("MainWindow", "0"))
        self.caiji.setText(_translate("MainWindow", "采集"))
        self.kai.setText(_translate("MainWindow", "开"))
        self.guan.setText(_translate("MainWindow", "关"))
        self.label_3.setText(_translate("MainWindow", "5组"))
import ziyuan_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
